### ISSUE TITLE
date stripping throws error

### ISSUE THREAD

**Issue by Toylerrr** [Phalcode/rawg-to-steam-redirect#1]
Unsure if this is a USA to Germany date formatting error 

"Oct 27, 2016" is what steam api shows as the date when I query [this ](https://store.steampowered.com/api/appdetails?appids=489830)

released = datetime.datetime.strptime(released, '**%d %b**, %Y').strftime('%Y-%m-%dT%H:%M:%SZ')

Throws errors
ValueError: time data 'Oct 27, 2016' does not match format '%d %b, %Y'

 because it should be for US dates

released = datetime.datetime.strptime(released, '**%b %d**, %Y').strftime('%Y-%m-%dT%H:%M:%SZ')

I didn't want to commit the change if its a regional thing that we need to figure out.

**Comment by Alfagun74** [comment]
fixed in v5
